# -*- coding: utf-8 -*-
"""proyectoCert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UNRH1u288kq-yrOI9dIyFcY44tnQx09F

**Modelo de clasificación de reseñas de películas**

Enmanuel Méndez Guzmán
"""

#Importar librerías
import nltk
from nltk.corpus import movie_reviews

# Descargar dataset
nltk.download('movie_reviews')

#Listas para guardar las reseñas y etiquetas
resenas = []
etiquetas = []

#Recorrer el dataset y asignar etiquetas
for fileid in movie_reviews.fileids():
    text = movie_reviews.raw(fileid)
    resenas.append(text)
    etiquetas.append(1 if fileid.startswith("pos") else 0)
    # 1 es positivo, 0 es negativo

#Entrenamiento y prueba
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    resenas, etiquetas, test_size=0.2, random_state=42
)

#Vectorización
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=10000,
    stop_words="english",
    ngram_range=(1, 2)
)
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

#Entrenar el modelo: Regresión
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=200)
model.fit(X_train_vec, y_train)

#Evaluación del modelo
from sklearn.metrics import accuracy_score, classification_report

pred = model.predict(X_test_vec)
print("Exactitud:", accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

#Función de predicción
def predecir_sentimiento(texto):
    texto_vec = vectorizer.transform([texto])
    pred = model.predict(texto_vec)[0]
    return "Positiva :)" if pred == 1 else "Negativa :("

#Pruebas
#Nota: el modelo funciona mejor con frases más largas y solo reconoce frases en inglés porque el dataset está en inglés
print(predecir_sentimiento("The movie was exciting and the experience was out of this world"))
print(predecir_sentimiento("The movie was bad"))


import joblib

joblib.dump(model, "modelo_sentimientos.pkl")
joblib.dump(vectorizer, "vectorizador.pkl")
